export const tags = [
  {
    name: 'infrastructure',
    foreColor: '#F600FB',
    bgColor: '#F1C0F2',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'defi',
    foreColor: '#BA00FB',
    bgColor: '#E5C0F2',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'metaverse',
    foreColor: '#6E00FB',
    bgColor: '#D6C0F2',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'guild',
    foreColor: '#19BEA1',
    bgColor: '#C2EDE5',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'nft',
    foreColor: '#6FC700',
    bgColor: '#CBE6AA',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'dao',
    foreColor: '#EDBD2F',
    bgColor: '#EFE1B6',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'launchpad',
    foreColor: '#764A08',
    bgColor: '#CBBEAA',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'marketplace',
    foreColor: '#FF9900',
    bgColor: '#F4D6A8',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'entertainment',
    foreColor: '#DD2902',
    bgColor: '#EAB4A9',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'blockchain service',
    foreColor: '#FD4242',
    bgColor: '#F4BCBC',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'trading',
    foreColor: '#C97800',
    bgColor: '#E4CCA8',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'gaming',
    foreColor: '#FB007B',
    bgColor: '#EBC0D5',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'financial service',
    foreColor: '#561F9C',
    bgColor: '#C2B1D7',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'dex',
    foreColor: '#0500FB',
    bgColor: '#C1C0F2',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'social network',
    foreColor: '#0055FB',
    bgColor: '#C0D1F2',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'moba',
    foreColor: '#2090F8',
    bgColor: '#CCE0F2',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'exchange',
    foreColor: '#1E9882',
    bgColor: '#C6DEDA',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'market',
    foreColor: '#12A64D',
    bgColor: '#C4E1CF',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'protocol',
    foreColor: '#C3B002',
    bgColor: '#E2DDA9',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'dapp',
    foreColor: '#7A6F0E',
    bgColor: '#CDC9AC',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'security',
    foreColor: '#FB620B',
    bgColor: '#F3C5AB',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'investing',
    foreColor: '#AD3E00',
    bgColor: '#DCBBA8',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

